version: "3.9"

volumes:
  postgres:

services:
  postgres:
    image: postgres:15.2

    volumes:
      - postgres:/var/lib/postgresql/data

    environment:
      POSTGRES_DB: keycloakDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    command: -h "postgres" -p "5432"
    restart: unless-stopped

  keycloak:
    build:
      context: .
      dockerfile: ./Backend/KeyCloak/DockerFile

    volumes:
      - ./Backend/KeyCloak/realmImports:/opt/keycloak/data/import

    environment:
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/data_analytics-realm.json
      #KC_DB: postgres # в отдельном докер файле из-за bug Keycloak https://github.com/keycloak/keycloak/issues/15898
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_DB_URL_DATABASE: keycloakDB
      KC_DB_SCHEMA: public
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432      
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
#      KC_HOSTNAME: keycloak не стоит указывать так перестаёт открываться консоль админа
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_PROXY: edge
      KC_LOG_LEVEL: WARN
      KC_HEALTH_ENABLED: false
      ENV KC_METRICS_ENABLED: false
    ports:
      - "8080:8080"
    command: "start --optimized --import-realm"

    restart: unless-stopped
    depends_on:
      - postgres

  schoolbackend:
    build: 
      context: .
      dockerfile: ./Backend/Backend.WebApi/Dockerfile
    ports:
      - "80:80"
      - "5041:5041"
    environment:
      ASPNETCORE_ENVIRONMENT: Development #Development используется для переопределения конфигов под Docker 
    restart: unless-stopped

    depends_on:
      - postgres
      - keycloak
  schoolfrontend:
    build:
      context: .
      dockerfile: ./lab2/Dockerfile
    ports:
      - "3000:3000" 
    restart: unless-stopped